conky.config = {
    out_to_x = false,
    out_to_wayland = true,
    alignment = 'top_left',
    xinerama_head = tonumber(os.getenv('CONKY_HEAD')) or 0,
    font = 'Mononoki Nerd Font:size=11',
    gap_x = 50,
    gap_y = 50,
    maximum_width = 370,
    own_window_transparent = true
}

conky.text = [[
${font Mononoki Nerd Font:size=11}${time %H:%M}${font}${alignr}${color grey}$nodename${color}
${color grey}${time %A, %d %b %Y}${color}

+---------------------------------------+
| 󰻠 System
+---------------------------------------+
| ${color grey}󰥔 Uptime:    ${color} $uptime
| ${color grey}󰻠 CPU:       ${color} ${color #f38ba8}$cpu%${color} ${hwmon coretemp temp 1}°C
| ${color grey}󰻠 Frequency: ${color} $freq MHz
| ${color grey}󰢮 GPU:       ${color} Iris Xe
| ${color grey}󰢮 GPU Freq:  ${color} ${execi 5 cat /sys/class/drm/card1/gt_cur_freq_mhz} / ${execi 60 cat /sys/class/drm/card1/gt_max_freq_mhz} MHz
| ${color grey}󰍛 RAM:       ${color} $memperc%
| ${color grey}󰍛 RAM used:  ${color} $mem / $memmax
| ${color grey}󰘚 Swap:      ${color} $swapperc%
| ${color grey}󰘚 Swap used: ${color} $swap / $swapmax
| ${color grey}󱊣 Battery:   ${color} ${if_match ${battery_percent BAT0} < 20}${color #f38ba8}${endif}${battery_percent BAT0}%${color} ${execi 30 ~/.config/conky/battery_time.sh}
| ${color grey}󰓅 Processes: ${color} $running_processes / $processes
+---------------------------------------+
${if_match ${cpu cpu0} > 80}${color #ff5555}[!!!] High CPU load${color}${endif}

+---------------------------------------+
| 󰩟 Network
+---------------------------------------+
| ${color grey}Iface:       ${color} ${gw_iface}
| ${color grey}Physical IP: ${color} ${addr enp85s0}
${execpi 10 ~/.config/conky/vpn_info.sh}
| ${color grey}Public:      ${color} ${execi 300 curl -fsS --max-time 3 https://api.ipify.org || echo N/A}
| ${color grey}Up:          ${color} ${upspeed ${gw_iface}}/s
| ${color grey}Down:        ${color} ${downspeed ${gw_iface}}/s
+---------------------------------------+

+---------------------------------------+
| 󰋋 Audio Devices                       |
+---------------------------------------+
${execpi 10 ~/.config/conky/audio_devices.sh}
+---------------------------------------+

+---------------------------------------+
${execpi 15 ~/.config/conky/bluetooth_devices.sh}
+---------------------------------------+
]]
