conky.config = {
    out_to_x = false,
    out_to_wayland = true,
    alignment = 'top_right',
    xinerama_head = tonumber(os.getenv('CONKY_HEAD')) or 0,
    font = 'Mononoki Nerd Font:size=11',
    gap_x = 50,
    gap_y = 50,
    maximum_width = 370,
    own_window_transparent = true
}

conky.text = [[
+---------------------------------------+
| 󰣇 OS                                  |
+---------------------------------------+
| ${color grey}Distro:${color} Arch Linux
| ${color grey}Kernel:${color} $kernel
| ${color grey}Arch:${color} $machine
| ${color grey}Pacman pkgs:${color} ${execi 1800 pacman -Qq | wc -l}
| ${color grey}AUR pkgs:${color} ${execi 1800 pacman -Qm | wc -l}
+---------------------------------------+

+---------------------------------------+
| 󰋊 Storage                             |
+---------------------------------------+
| ${color grey}/     ${color} ${fs_used /} used (${fs_used_perc /}%) / ${fs_free /} free
| ${color grey}/home ${color} ${fs_used /home} used (${fs_used_perc /home}%) / ${fs_free /home} free
| ${color grey}/vms  ${color} ${fs_used /vms} used (${fs_used_perc /vms}%) / ${fs_free /vms} free
| ${color grey}/files${color} ${fs_used /files} used (${fs_used_perc /files}%) / ${fs_free /files} free
+---------------------------------------+

+---------------------------------------+
| 󰍛 Top Memory                          |
+---------------------------------------+
${execpi 5 ~/.config/conky/top_processes.sh mem 5}
+---------------------------------------+

+---------------------------------------+
| 󰓅 Top CPU                             |
+---------------------------------------+
${execpi 5 ~/.config/conky/top_processes.sh cpu 5}
+---------------------------------------+

+---------------------------------------+
| 󰠓 Crypto                              |
+---------------------------------------+
${execpi 3600 ~/.config/conky/crypto.sh}
+---------------------------------------+
]]
